name: "Konstantinos Tseas"
description: "A website for the course of WWW."
url: "http://kotseas.github.io"
paginate: 9
baseurl: /kotseas.github.io
markdown: rdiscount
safe: true
lsi: false
pygments: true
